services:
  logs-melhor-envio-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: logs-melhor-envio-api
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - ./log_files:/usr/src/app/log_files
    networks:
      - app_network
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/logs_reports
    depends_on:
      postgres:
        condition: service_healthy
    command: sh -c "npx prisma migrate deploy && npm run start:dev"
    restart: unless-stopped

  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: logs_reports
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - app_network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  app_network:
    driver: bridge
